Nutrimenez/Nutrimenez/Controllers/ConsultasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nutrimenez.Data;
using Nutrimenez.Models;

namespace Nutrimenez.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ConsultasController : Controller
    {
        private readonly NutrimenezContexto _context;

        public ConsultasController(NutrimenezContexto context)
        {
            _context = context;
        }

        // GET: Consultas
        public async Task<IActionResult> Index(string strCadenaBusqueda, string busquedaActual, int? intTipoConsultaId, 
            int? tipoConsultaIdActual,int? pageNumber)
        {
            if (strCadenaBusqueda != null)
            {
                pageNumber = 1;
            }
            else
            {
                strCadenaBusqueda = busquedaActual;
            }

                ViewData["BusquedaActual"] = strCadenaBusqueda;

            if (intTipoConsultaId != null)
            {
                pageNumber = 1;
            }
            else
            {
                intTipoConsultaId = tipoConsultaIdActual;
            }
            ViewData["TipoConsultaIdActual"] = intTipoConsultaId;

            // Cargar datos de los avisos
            var consultas = _context.Consultas.AsQueryable();

            // Ordenar descendente por FechaAviso
            consultas = consultas.OrderByDescending(s => s.TipoConsulta);

            // Para buscar avisos por nombre de empleado en la lista de valores
            if (!String.IsNullOrEmpty(strCadenaBusqueda))
            {
                consultas = consultas.Where(s => s.Usuario.Nombre.Contains(strCadenaBusqueda));
            }

            //para filtrar avisos por tipo de avería
            if(intTipoConsultaId == null)
            {
                ViewData["TipoConsultaId"] = new SelectList(_context.TipoConsultas, "Id", "Descripcion");
            }
            else
            {
                ViewData["TipoConsultaId"] = new SelectList(_context.TipoConsultas, "Id", "Descripcion", intTipoConsultaId);
                consultas = consultas.Where(x => x.TipoConsultaId == intTipoConsultaId);
            }

            consultas = consultas.Include(a => a.Usuario)
                                 .Include(a => a.TipoConsulta);

            int pageSize = 5;
            return View(await PaginatedList<Consulta>.CreateAsync(consultas.AsNoTracking(),
                pageNumber ?? 1, pageSize));

            //return View(await consultas.AsNoTracking().ToListAsync());


            //var nutrimenezContexto = _context.Consultas.Include(c => c.TipoConsulta).Include(c => c.Usuario);
            //return View(await nutrimenezContexto.ToListAsync());
        }

        // GET: Consultas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consulta = await _context.Consultas
                .Include(c => c.TipoConsulta)
                .Include(c => c.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consulta == null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        // GET: Consultas/Create
        public IActionResult Create()
        {
            ViewData["TipoConsultaId"] = new SelectList(_context.TipoConsultas, "Id", "Descripcion");
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Nombre");
            return View();
        }

        // POST: Consultas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descripcion,FechaAviso,UsuarioId,TipoConsultaId")] Consulta consulta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(consulta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoConsultaId"] = new SelectList(_context.TipoConsultas, "Id", "Descripcion", consulta.TipoConsultaId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Nombre", consulta.UsuarioId);
            return View(consulta);
        }

        // GET: Consultas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consulta = await _context.Consultas.FindAsync(id);
            if (consulta == null)
            {
                return NotFound();
            }
            ViewData["TipoConsultaId"] = new SelectList(_context.TipoConsultas, "Id", "Descripcion", consulta.TipoConsultaId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Nombre", consulta.UsuarioId);
            return View(consulta);
        }

        // POST: Consultas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descripcion,FechaAviso,UsuarioId,TipoConsultaId")] Consulta consulta)
        {
            if (id != consulta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consulta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsultaExists(consulta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoConsultaId"] = new SelectList(_context.TipoConsultas, "Id", "Descripcion", consulta.TipoConsultaId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Nombre", consulta.UsuarioId);
            return View(consulta);
        }

        // GET: Consultas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consulta = await _context.Consultas
                .Include(c => c.TipoConsulta)
                .Include(c => c.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consulta == null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        // POST: Consultas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var consulta = await _context.Consultas.FindAsync(id);
            _context.Consultas.Remove(consulta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConsultaExists(int id)
        {
            return _context.Consultas.Any(e => e.Id == id);
        }
    }
}

Nutrimenez/Nutrimenez/Controllers/MisDatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nutrimenez.Data;
using Nutrimenez.Models;

namespace Nutrimenez.Controllers
{
    [Authorize(Roles = "Usuario")]
    public class MisDatosController : Controller
    {
        private readonly NutrimenezContexto _context;
        public MisDatosController(NutrimenezContexto context)
        {
            _context = context;
        }
        // GET: MisDatos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MisDatos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
       Create([Bind("Id,Nombre,Email,Telefono,FechaNacimiento")] Usuario usuario)
        {
            // Asignar el Email del usuario
            usuario.Email = User.Identity.Name;
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(usuario);
        }

        // GET: MisDatos/Edit
        public async Task<IActionResult> Edit()
        {
            // Se seleccioanan datos del usuario correspondiente al emplead actual
            string emailUsuario = User.Identity.Name;
            Usuario usuario = await _context.Usuarios
            .Where(e => e.Email == emailUsuario)
            .FirstOrDefaultAsync();
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }
        // POST: MisDatos/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
         [Bind("Id,Nombre,Email,Telefono,FechaNacimiento")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(usuario);
        }
        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }
    }

}

Nutrimenez/Nutrimenez/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nutrimenez.Data;
using Nutrimenez.Models;

namespace Nutrimenez.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsuariosController : Controller
    {
        private readonly NutrimenezContexto _context;

        public UsuariosController(NutrimenezContexto context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index(int? pageNumber)
        {
            // Cargar datos de Empleados
            var usuarios = from s in _context.Usuarios
                            select s;
            int pageSize = 3;
            return View(await PaginatedList<Usuario>.CreateAsync(usuarios.AsNoTracking(),
            pageNumber ?? 1, pageSize));

            // return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Email,Telefono,FechaNacimiento")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Email,Telefono,FechaNacimiento")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }
    }
}

Nutrimenez/Nutrimenez/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nutrimenez</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="~/https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/assets/vendor/line-awesome/css/line-awesome.min.css" rel="stylesheet">
    <link href="~/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">



</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand font-main-green" asp-area="" asp-controller="Home" asp-action="Index"><strong>Nutrimenez</strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><span class="hover-link">Inicio</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Services"><span class="hover-link">Servicios</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About"><span class="hover-link">Sobre Mí</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact"><span class="hover-link">Contacto</span></a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Usuario"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Configuración</a>

                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="MisDatos" asp-action="Edit">Mis Datos</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="MisConsultas" asp-action="Index">Mis Consultas</a>
                                    </div>

                                </li>

                            }
                            if (User.IsInRole("Administrador"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Configuración</a>

                                    <div class="dropdown-menu">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="RolesUsuario" asp-action="Index">Roles</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Consultas" asp-action="Index">Consultas</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="TipoConsultas" asp-action="Index">Tipos de Consulta</a>
                                    </div>

                                </li>
                            }

                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    



    <div class="container-fluid p-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 col-md-6 footer-info">
                        <h3>Nutrimenez</h3>
                        <p>Expertos en Nutrición deportiva.</p>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-links">
                        <h4>Enlaces de Interés</h4>
                        <ul>
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="Services">Servicios</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="About">Sobre Mí</a>
                            </li>
                            

                            <li><a href="#">Términos de Servicio</a></li>

                            <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidad</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-contact">
                        <a asp-area="" asp-controller="Home" asp-action="Contact"><h4 class="hover-link">Contacto</h4></a>
                        <p>
                            Alicante (Alicante) <br>
                            03007<br>
                            <strong>Email:</strong> info@nutrimenez.es<br>
                        </p>

                        <div class="social-links">
                            <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Nutrimenez</span></strong>. Todos los derechos Reservados
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/serenity-bootstrap-corporate-template/ -->
                Diseñado por <a href="https://bootstrapmade.com/">Carlos González Mújica</a>
            </div>
        </div>
    </footer><!-- End Footer -->
    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Nutrimenez - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>-->
    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/assets/vendor/counterup/counterup.min.js"></script>
    <script src="~/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>